// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDByDBBOTxhxRU3fjRqrY5lW1RfSuQhD6c',
    appId: '1:506616403990:web:75abd6330e33c463a87d37',
    messagingSenderId: '506616403990',
    projectId: 'studentverse-bc89e',
    authDomain: 'studentverse-bc89e.firebaseapp.com',
    storageBucket: 'studentverse-bc89e.firebasestorage.app',
    measurementId: 'G-VR57CCTB1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzL1QSgSNi2YjiUEuZMWLMq7pYQw17rSk',
    appId: 'AIzaSyBGZpbWH2RmlHUDAzNQ7NhfUL1dFF2J7bY',
    messagingSenderId: '506616403990',
    projectId: 'studentverse-bc89e',
    storageBucket: 'studentverse-bc89e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMCzHBeAp0dUcuV0z0UNNGn0fGhRdXk9U',
    appId: '1:506616403990:ios:04b3e2d49b1c8ffaa87d37',
    messagingSenderId: '506616403990',
    projectId: 'studentverse-bc89e',
    storageBucket: 'studentverse-bc89e.firebasestorage.app',
    iosBundleId: 'com.example.studentverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9tyvWUF3piYRUICYru8VPAXYntR_m6HU',
    appId: '1:506616403990:ios:04b3e2d49b1c8ffaa87d37',
    messagingSenderId: '506616403990',
    projectId: 'studentverse-bc89e',
    storageBucket: 'studentverse-bc89e.firebasestorage.app',
    iosBundleId: 'com.example.studentverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtHDMGGtHFYR7xVdLRodMj2FYrk35M0bo',
    appId: '1:506616403990:web:f43a9e8210f1d5b6a87d37',
    messagingSenderId: '506616403990',
    projectId: 'studentverse-bc89e',
    authDomain: 'studentverse-bc89e.firebaseapp.com',
    storageBucket: 'studentverse-bc89e.firebasestorage.app',
    measurementId: 'G-FYJ388SL5X',
  );
}
