import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart'; // ← Add this line for Provider

import 'routes/app_routes.dart'; // Route names and route mappings
import 'core/theme/app_theme.dart'; // Custom light/dark theme
import 'firebase_options.dart'; // Firebase options generated by CLI
import 'theme/theme_provider.dart'; // ← Add this import
import 'package:flutter_dotenv/flutter_dotenv.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

 await dotenv.load(fileName: ".env");

  // Initialize Firebase with environment-based options
  await Firebase.initializeApp(
    options: FirebaseOptions(
      apiKey: dotenv.env['API_KEY']!,
      appId: dotenv.env['APP_ID']!,
      messagingSenderId: dotenv.env['MESSAGING_SENDER_ID']!,
      projectId: dotenv.env['PROJECT_ID']!,
      storageBucket: dotenv.env['STORAGE_BUCKET'] ??'',
    ),
  );


  // Run the main app
  runApp(
    ChangeNotifierProvider(
      create: (_) => ThemeProvider(), // Provide theme state globally
      child: const StudentVerseApp(),
    ),
  );
}

class StudentVerseApp extends StatelessWidget {
  const StudentVerseApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context); // Access theme

    return MaterialApp(
      title: 'StudentVerse',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme, // Defined in app_theme.dart
      darkTheme: AppTheme.darkTheme, // Also from app_theme.dart
      themeMode: themeProvider.themeMode, // Dynamic switching
      initialRoute: AppRoutes.login, // You can change this to splash if needed
      routes: AppRoutes.routes,
    );
  }
}
